import { WeatherKey, WeatherPreset } from './types';

export const WEATHER_PRESETS: Record<WeatherKey, WeatherPreset> = {
  sunny: {
    key: 'sunny',
    label: 'Harmattan Sun',
    icon: '☀️',
    skyColor: 0xf3c98b,
    fogColor: 0xf3c98b,
    fogNear: 70,
    fogFar: 320,
    sunColor: 0xffe2b0,
    sunIntensity: 0.95,
    sunPos: [-20, 36, -50],
    ambientColor: 0xfff1d6,
    ambientIntensity: 0.85,
    rainIntensity: 0,
    dustIntensity: 0.05,
    roadFriction: 1.0,
    fareMultiplier: 1.0,
    description: 'Golden sunlight over the highway with views of Zuma Rock',
    temp: '34°C',
  },
  sunset: {
    key: 'sunset',
    label: 'Abuja Dusk',
    icon: '🌅',
    skyColor: 0xd9532f,
    fogColor: 0xc85a32,
    fogNear: 55,
    fogFar: 260,
    sunColor: 0xff8c42,
    sunIntensity: 0.8,
    sunPos: [15, 14, -260],
    ambientColor: 0x9b51e0,
    ambientIntensity: 0.65,
    rainIntensity: 0,
    dustIntensity: 0.08,
    roadFriction: 1.0,
    fareMultiplier: 1.15,
    description: 'Rush hour golden twilight as streetlights begin to flicker on',
    temp: '29°C',
  },
  rain: {
    key: 'rain',
    label: 'Tropical Rain',
    icon: '🌧️',
    skyColor: 0x3d4b56,
    fogColor: 0x34414b,
    fogNear: 45,
    fogFar: 190,
    sunColor: 0x829ab1,
    sunIntensity: 0.45,
    sunPos: [-10, 25, -40],
    ambientColor: 0x486581,
    ambientIntensity: 0.55,
    rainIntensity: 0.7,
    dustIntensity: 0,
    roadFriction: 0.82,
    fareMultiplier: 1.3,
    description: 'Heavy tropical downpour · slippery asphalt & water puddle splashes',
    temp: '24°C',
  },
  thunderstorm: {
    key: 'thunderstorm',
    label: 'Thunderstorm',
    icon: '⛈️',
    skyColor: 0x1b242c,
    fogColor: 0x171f26,
    fogNear: 32,
    fogFar: 145,
    sunColor: 0x627d98,
    sunIntensity: 0.25,
    sunPos: [-10, 25, -40],
    ambientColor: 0x243b53,
    ambientIntensity: 0.38,
    rainIntensity: 1.0,
    dustIntensity: 0,
    roadFriction: 0.74,
    fareMultiplier: 1.5,
    description: 'Severe thunder squall · sudden lightning flashes & +50% storm hazard fare',
    temp: '22°C',
  },
  night: {
    key: 'night',
    label: 'Midnight Express',
    icon: '🌙',
    skyColor: 0x07111e,
    fogColor: 0x050c15,
    fogNear: 45,
    fogFar: 200,
    sunColor: 0x1e3a5f,
    sunIntensity: 0.22,
    sunPos: [0, 40, -100],
    ambientColor: 0x102a43,
    ambientIntensity: 0.35,
    rainIntensity: 0,
    dustIntensity: 0.02,
    roadFriction: 1.0,
    fareMultiplier: 1.25,
    description: 'Starry midnight highway illuminated by sodium streetlamps and vehicle headlights',
    temp: '25°C',
  },
  harmattan: {
    key: 'harmattan',
    label: 'Harmattan Haze',
    icon: '🌫️',
    skyColor: 0xdec18c,
    fogColor: 0xd4b075,
    fogNear: 28,
    fogFar: 135,
    sunColor: 0xffe8ba,
    sunIntensity: 0.58,
    sunPos: [0, 30, -100],
    ambientColor: 0xc29b62,
    ambientIntensity: 0.65,
    rainIntensity: 0,
    dustIntensity: 0.85,
    roadFriction: 0.94,
    fareMultiplier: 1.1,
    description: 'Dense Saharan dust storm blowing across the FCT with reduced visibility',
    temp: '31°C',
  },
};

export const WEATHER_ORDER: WeatherKey[] = [
  'sunny',
  'sunset',
  'thunderstorm',
  'rain',
  'night',
  'harmattan',
];
